### ISSUE TITLE
点击全屏按钮报错：cannot read properties of undefined (reading 'requestFullscreen)

### ISSUE THREAD

**Issue by tzfun** [tzfun/vue-web-terminal#10]
点击全屏按钮报错：cannot read properties of undefined (reading 'requestFullscreen),最小化和关闭按钮没问题，前面做好的也不能用了

_Originally posted by @18030705033 in https://github.com/tzfun/vue-web-terminal/issues/9#issuecomment-1288991483_

**Comment by tzfun** [comment]
@18030705033 提供一下运行的浏览器版本和报错堆栈

**Comment by 18030705033** [comment]
谷歌浏览器，版本号104.0.5112.81，报错是  at proxy._fllscreen(vue-web-terminal.js:16:64717) 
at proxy._triggerClick(vue-web-terminal.js:56044)
还有个at Y.e3.showHeader.onClick.t3<computed>.t3(vue-web-terminal.js:16:42917)

**Comment by 18030705033** [comment]
还有大佬，有销毁组件的方法调用吗？你这边点击close是咋个做的呢。现在只能监听到onClick传递过来的key

**Comment by tzfun** [comment]
确实是一个bug，我待会发布一个新版本

**Comment by 18030705033** [comment]
在执行命令的时候开始报错cannot read properties of undefined(reading 'scrollTop')&nbsp; at proxy.<anonymous&gt;(vue-web-terminal.js:16:59776)&nbsp; 这个是我哪里配置错了吗
&nbsp;


小宾。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月25日(星期二) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tzfun/vue-web-terminal] 点击全屏按钮报错：cannot read properties of undefined (reading &#39;requestFullscreen) (Issue #10)





 
确实是一个bug，我待会发布一个新版本

**Comment by tzfun** [comment]
> 还有大佬，有销毁组件的方法调用吗？你这边点击close是咋个做的呢。现在只能监听到onClick传递过来的key

销毁组件可以用`v-if`或者`key`来控制

**Comment by tzfun** [comment]
> 在执行命令的时候开始报错cannot read properties of undefined(reading 'scrollTop')&nbsp; at proxy.<anonymous&gt;(vue-web-terminal.js:16:59776)&nbsp; 这个是我哪里配置错了吗

这个问题在`3.0.9`版本修复了

**Comment by 18030705033** [comment]
实际操作，如果用v-if，elements  组件所在地方用v-if是新创建和删除了的。但是如果新创建的name和上一个是相同的就会报错 unable to register anexisting terminal :'上次用的名字'   at Object.o2[as register](vue-web-terminal.js:16 :54247),现目前只能先将name做成变量，每次用不同的name，

**Comment by 18030705033** [comment]
会报黄错 component emitted event "initBefore" but it is neither declared in the emits option nor as an onInitBefor prop，和initComplete  是因为这个吗

**Comment by tzfun** [comment]
> 实际操作，如果用v-if，elements 组件所在地方用v-if是新创建和删除了的。但是如果新创建的name和上一个是相同的就会报错 unable to register anexisting terminal :'上次用的名字' at Object.o2[as register](vue-web-terminal.js:16 :54247),现目前只能先将name做成变量，每次用不同的name，

你可以提交一个新的issue然后附上简单的demo代码看一下，应该是你哪个地方写法不对，导致没有正常销毁插件实例，我写了demo并且在自己的项目中也没有遇到这种情况。对于initBefore和initComplete警告和这个没关系，这个警告是提示没有注册生命周期事件，在你的代码中加上`@initBefore`和`@initComplete`事件就可以了
