### ISSUE TITLE
提示框初始化位置超出可视框

### ISSUE THREAD

**Issue by redisviewer** [tzfun/vue-web-terminal#105]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/d849a148-5023-4c3e-aeca-cf9c1fa1e448">

命令返回数量稍多，正在向下滚动的过程中，这时输入命令，候选命令弹出会卡屏

**Comment by tzfun** [comment]
`2.3.1`和`3.3.1`版本已更新
