### ISSUE TITLE
光标位置不准确

### ISSUE THREAD

**Issue by akaiuo** [tzfun/vue-web-terminal#106]
行间字体默认居中，我想改为靠左，不知道怎么改
![屏幕截图 2024-08-07 225247](https://github.com/user-attachments/assets/6e3f969d-f370-460c-9c79-1c19b93e2139)

在向左移动光标时候显示位置错误
![屏幕截图 2024-08-07 225017](https://github.com/user-attachments/assets/42a77373-3cc8-4197-84cc-b451806a24b3)

代码是在文档中的快速上手cv下来的，几乎没怎么改

**Comment by tzfun** [comment]
这是你的父元素样式影响到了，检查一下父级标签的css样式，比如body、html、#app等
