### ISSUE TITLE
一次性输入多个中文或者英文，就会出现光标定位不追求问题

### ISSUE THREAD

**Issue by lw-742787938** [tzfun/vue-web-terminal#107]
一次性输入多个中文或者英文，就会出现光标定位不追求问题
![Snipaste_2024-08-23_17-18-05](https://github.com/user-attachments/assets/b0ce5d65-b6e9-45c3-83fb-881c96dfa2c0)

**Comment by tzfun** [comment]
中文输入法会修改光标位置，是跟系统相关的，之前有人遇到过，目前暂时没有好的办法处理这个问题

**Comment by Chener-03** [comment]
> 中文输入法会修改光标位置，是跟系统相关的，之前有人遇到过，目前暂时没有好的办法处理这个问题

移动端输入英文也会出现这种情况  光标始终在首位

**Comment by tzfun** [comment]
已发布 `2.3.3` 和 `3.3.3` 版本更新

**Comment by tzfun** [comment]
@lw-742787938 
中文输入问题已发布 `3.3.4-rc.4` 版本解决，此版本与上个release版本 `3.3.3` 差别仅在于解决中文输入问题
