### ISSUE TITLE
鼠标右键粘贴内容，只会粘贴到文本尾而不是随光标位置粘贴

### ISSUE THREAD

**Issue by imchilexu** [tzfun/vue-web-terminal#116]
鼠标右键粘贴内容，只会粘贴到文本尾，而不是随光标位置粘贴。
不管鼠标光标移动到哪个位置，右击总是粘贴到末尾，再次移动光标，光标重置到末尾

**Comment by tzfun** [comment]
已发布 `2.3.3` 和 `3.3.3` 版本更新
