### ISSUE TITLE
关闭组件后新创建name重复

### ISSUE THREAD

**Issue by 18030705033** [tzfun/vue-web-terminal#12]
用v-if控制组件  <Terminal v-if="flag" name="bbb" @onClick="clickTerminal"/>，当点击关闭按钮
const clickTerminal=(key:string)=>{
  if(key=='close'){
    flag.value=false
  }
}
然后重新创建组件，会报错                     Uncaught (in promise) Error: Unable to register an existing terminal: bbb
![ef42b69dec1a3abe23dabd269eba5af](https://user-images.githubusercontent.com/72338420/197914465-9f6b8783-07bb-4d6d-9d8d-73cb84cfeea3.jpg)
![83437596bf315fa3b4249c64d2ae04d](https://user-images.githubusercontent.com/72338420/197914469-b5871d1d-ece1-4720-b4f3-71c3205a9ee6.jpg)

    at Object.o2 [as register] (vue-web-terminal.js:16:51058)
这是今天新创建的一个demo，只有helloWolrd的那种

**Comment by tzfun** [comment]
确定了这是一个仅存在于vue3版本的bug，稍后我会修复这个问题并发布新的版本。

**Comment by tzfun** [comment]
@18030705033 已发布`3.0.10`版本修复

**Comment by 18030705033** [comment]
大佬威武
