### ISSUE TITLE
两个用户交互问题

### ISSUE THREAD

**Issue by passerbyzed** [tzfun/vue-web-terminal#126]
1. terminal界面只能复制当前输入行之前的内容，当前行前内容无法复制
2. 复制快捷键ctrl + insert无法生效，而粘贴快捷键shift + insert可以生效

**Comment by tzfun** [comment]
1. 描述有点让人费解，你是指无法复制当前输入行之前的上下文（context）部分吗？这部分确实无法复制的，历史原因当初特意频闭了选中复制，不过现在应该可以开放了
2. 复制粘贴的快捷键只支持了 `ctrl+c` 和 `ctrl + v`，insert键只在部分键盘上才有所以并未支持

**Comment by passerbyzed** [comment]
1. 你的理解是对的，感谢解答
2. 考虑这个问题的原因有如下两点：
   1. 部分linux操作系统使用者更习惯使用ctrl + insert和shift + insert
   2. 在linux图形化操作系统（如ubuntu）上无法使用复制粘贴快捷键操作vue-web-termina

**Comment by passerbyzed** [comment]
不好意思，有点先入为主了，刚刚在ubuntu虚拟机上试了一下，专属快捷键也可以复制粘贴

**Comment by tzfun** [comment]
> 不好意思，有点先入为主了，刚刚在ubuntu虚拟机上试了一下，专属快捷键也可以复制粘贴

没问题，欢迎提出任何意见，毕竟我测试环境也难以覆盖全面。

另外鼠标右键也可以复制粘贴，你可以尝试一下
