### ISSUE TITLE
优化：最新行在可视区域内自动跳转到底部，否则不自动跳转

### ISSUE THREAD

**Issue by navishachiku** [tzfun/vue-web-terminal#128]
我目前使用做为 MQTT 消息的监听

但有时候会有需求来查看被卷动上去的历史消息

由于 MQTT 会持续 `pushMessage`，所以导致 `_jumpToBottom()` 也不断被触发，而无法回头查看消息

希望可以透过 `scrollMode` 来切换暂时停止滚动

**Comment by tzfun** [comment]
scrollMode为none有其他意义，这么设计不太合适。

有一个处理方式不知道能不能解决你的问题：当最新一行在可视区域内就自动跳到底部，否则就不自动跳转

**Comment by navishachiku** [comment]
> scrollMode为none有其他意义，这么设计不太合适。
> 
> 有一个处理方式不知道能不能解决你的问题：当最新一行在可视区域内就自动跳到底部，否则就不自动跳转

可以的，不如说这是我期望的更完整的解决方案。

我原本是打算用上面scrollMode的模式再接着拼出如你描述的这个功能

但若你能直接提供这个解决方法的话就更好了，谢谢！

**Comment by tzfun** [comment]
OK，这个作为一个优化项在下个版本更新

**Comment by tzfun** [comment]
已发布 `2.3.3` 和 `3.3.3` 版本更新
