### ISSUE TITLE
🎉计划在下个版本新增Shell组件，将支持ANSI样式输出，直接对接SSH输入输出。It is planned to add a new Shell component in the next version, which will support ANSI code output and directly connect to SSH input and output.

### ISSUE THREAD

**Issue by tzfun** [tzfun/vue-web-terminal#14]
计划在`2.2.x`和`3.2.x`版本新增Shell组件，保留和Terminal共有的全屏、拖拽外围功能，其内部控制台显示区域将重新实现，计划支持ANSI的部分样式和光标定位规则，输入输出可直接接入SSH，无需再做字符过滤。

此版本计划对现有代码进行优化重构，对现有的Terminal组件和API调用在使用方法上有较大调整，升级此版本需要修改对应的使用方式，后面会在文档中说明。

关于Shell组件更多你所期待或需求的功能可在此issue留言~

**Comment by GeekSRE** [comment]
您好，请问进展如何？预计什么时候上线，感谢。

**Comment by tzfun** [comment]
> 您好，请问进展如何？预计什么时候上线，感谢。

目前已经实现显示和部分光标控制，部分模式控制待解决。时间在春节后了，因为个人时间原因上线时间目前不太确定，不过在Shell组件之前我会先对Terminal组件支持ANSI Code的显示规则功能。

**Comment by tzfun** [comment]
考虑到ANSI转译工作量较大，且需兼容的 terminal 版本较多，个人难以完成此项工程，暂时不做Shell组件

（经过尝试实现了大部分ANSI的转码，虽然能满足正常的ssh管理以及指令解析，但发现兼容性较差，还达不到通用的水平）
