### ISSUE TITLE
Support for multiline answers to questions

### ISSUE THREAD

**Issue by michaelKurowski** [tzfun/vue-web-terminal#15]
**Feature or optimization description**
Currently it's hard to imitate a file editor because the input for the question answer is a standard HTML input. A text area would allow for a multiline-edition.

To better visualize the issue here's the current size of the input (marked with a red color):
![image](https://user-images.githubusercontent.com/2772942/204143646-004fe220-fb83-4d16-b640-a4483dceb29f.png)

It would also be neat to be able to pre-fill the input so that one could put there current content of a file.

**Applicable scene**
File editors

**Comment by tzfun** [comment]
OK, actually, there were plans to do this feature, but it was delayed by the production of the Shell component, and I will support this feature in the next version as soon as possible.

**Comment by tzfun** [comment]
Already in [3.1.2](https://github.com/tzfun/vue-web-terminal/releases/tag/3.1.2) and [2.1.2](https://github.com/tzfun/vue-web-terminal/releases/tag/2.1.2)  version supports this feature, thanks for your suggestion

**Comment by tzfun** [comment]
To add the usage method, two new APIs are provided to open and close the text editor. To open, please call `textEditorOpen`, and to close, please call `textEditorClose`. Of course, the user can also click the button on the page to trigger the close. The following is an example of use:

```js
onExecCmd(key, command, success, failed) {
    //  ... some logic
    if (key === 'edit') {
        Terminal.$api.textEditorOpen(this.name, {
            content: 'Please edit this text file.',
            onClose: value => {
                success([
                    {
                        class: 'success',
                        content: "Edit saved successfully!"
                    },
                    {
                        type: 'code',
                        content: value
                    }
                ])
            }
        })
    }
}
```

For more usage methods, please check the documentation:
* [textEditorOpen](https://github.com/tzfun/vue-web-terminal#texteditoropen)
* [textEditorClose](https://github.com/tzfun/vue-web-terminal#texteditorclose)

**Comment by michaelKurowski** [comment]
Alright thanks! :)

**Comment by tzfun** [comment]
The text editor already supports custom styles, and it can be used after updating to version [2.1.3](https://github.com/tzfun/vue-web-terminal/releases/tag/2.1.3) or [3.1.3](https://github.com/tzfun/vue-web-terminal/releases/tag/3.1.3), and the effect can also be previewed in the [online demo](https://tzfun.github.io/vue-web-terminal/?cmd=edit)
