### ISSUE TITLE
使用方向上键获取上一条命令并执行之后，再次按上键获取不到这一条命令，而是这条命令的前一条

### ISSUE THREAD

**Issue by lshuq** [tzfun/vue-web-terminal#16]
使用方向上键获取上一条命令并执行之后，再次按上键获取不到这一条命令，而是这条命令的前一条
再次执行前一条命令的时候会出现这个情况，如果多按几次上键执行更早之前的命令则不会有这问题

当依次执行 command1 command2 command3之后
按压方向上键获取到command3并执行之后
再次按方向上键此时输入的是command2，而并不是command3，命令历史的位置没有重置
命令历史列表依然是command1，command2，command3
当历史命令只有一条时，重复上面过程，第二次获取不到命令，需要先按下键再按上键才能获取

当依次执行 command1 command2 command3之后
按压两次方向上键获取到command2并执行之后
再次按方向上键此时输入的是command2，是正常的
此时命令历史列表是command1，command2，command3，command2

建议在每一次执行后，都重置一下命令执行历史列表当前的下标

**Comment by tzfun** [comment]
这个是为了初期项目应用这样设计的，后来经过体验确实存在你所说的问题，随着功能增加这一块优化就被遗忘了，下个版本修复这个问题。

**Comment by tzfun** [comment]
这个问题已发布[2.1.3](https://github.com/tzfun/vue-web-terminal/releases/tag/2.1.3)、[3.1.3](https://github.com/tzfun/vue-web-terminal/releases/tag/3.1.3)版本更新解决
