### ISSUE TITLE
动态修改context影响光标显示位置

### ISSUE THREAD

**Issue by lshuq** [tzfun/vue-web-terminal#17]
初始化之后光标的起始位置就固定了，虽然可以修改context，但是修改完之后，再按方向左键或者Home键光标的位置与实际的输入位置无法对齐

**Comment by tzfun** [comment]
demo中无法复现这个问题，提供一下你的版本、运行环境以及代码示例

**Comment by lshuq** [comment]
版本 3.1.1 + vue3
<template>
  <terminal class="terminal"
            ref="term"
            :name="name"
            :context="prefix"
            :command-store="commands"
            :warn-log-count-limit="2000"
            @exec-cmd="onExecCmd"
            @on-keydown="onKeydown"
            style="word-break: break-word;"
            :init-log="initLog"></terminal>
</template>
使用 Terminal.$api.updateContext 也有一样的问题

**Comment by tzfun** [comment]
需要使用`context.sync`，你可以在demo中执行命令测试这个问题：`context hello`，demo中也是执行`updateContext`API来实现的，快捷demo地址：[demo修改context](https://tzfun.github.io/vue-web-terminal/?cmd=context%20hello)

```vue
<terminal class="terminal"
ref="term"
:name="name"
:context.sync="prefix"
:command-store="commands"
:warn-log-count-limit="2000"
@exec-cmd="onExecCmd"
@on-keydown="onKeydown"
style="word-break: break-word;"
:init-log="initLog">
</terminal>
```

**Comment by tzfun** [comment]
修改上下文这个功能目前有点鸡肋，也在下个版本优化一下

**Comment by tzfun** [comment]
这个问题已发布[2.1.3](https://github.com/tzfun/vue-web-terminal/releases/tag/2.1.3)、[3.1.3](https://github.com/tzfun/vue-web-terminal/releases/tag/3.1.3)版本更新优化
