### ISSUE TITLE
希望加上对typescript的类型支持 

### ISSUE THREAD

**Issue by sharebravery** [tzfun/vue-web-terminal#18]
**Feature or optimization description**

**Applicable scene**

**Comment by tzfun** [comment]
实现和使用的语言是无关的，你是希望源码支持ts还是使用层面支持ts？如果是使用的话请举出一些例子。

**Comment by sharebravery** [comment]
使用层面支持ts，拥有类型提示，类似这种提示
![image](https://user-images.githubusercontent.com/64069898/206600173-58b49614-2879-41d3-af19-8a6a7210ac1e.png)

**Comment by tzfun** [comment]
这个是IDE扫描了Dependence的源码后提示的，js也有类似的提示，但是需要源码，当然我不知道你这种样式的提示是否是ts独有的，如果是那么就需要源码用ts重构，并且在依赖包里打入source，改造成本与效益比太大目前暂时不考虑重构。后续出其他组件或者有重构计划的时候再考虑。

**Comment by birdmanmandbir** [comment]
ts支持开发完成，测试中 @sharebravery 
https://github.com/tzfun/vue-web-terminal/pull/22
