### ISSUE TITLE
官方样例中json深度下拉框无法点击

### ISSUE THREAD

**Issue by birdmanmandbir** [tzfun/vue-web-terminal#23]
**Bug description**
官方样例中json深度下拉框无法点击
看控制台是因为多了一个click监听器，但看不出来是哪里附加的

**Steps to reproduce**
1. 打开官方样例 https://tzfun.github.io/vue-web-terminal/
2. 输入json
3. 点击下拉框

**Screenshot**
![image](https://user-images.githubusercontent.com/48193000/208671232-c03a224a-297f-4b60-8cc3-7c0c66d85ca1.png)

**Reproduce environment:**
 - OS: Windows
 - Browser edge

**Comment by birdmanmandbir** [comment]
应该是最外部容器绑了点击事件，导致点内部下拉框时也会触发容器上的focus
不好处理，这个下拉框要不去掉吧，可以通过命令的方式来改深度
@tzfun

**Comment by birdmanmandbir** [comment]
@click换成@focus似乎就行

**Comment by tzfun** [comment]
这个问题可以解决，之前是好的后来版本迭代过程中bug了，功能还是不去掉，挺多应用场景需要，如果你那边不好处理留着我来解决吧

**Comment by birdmanmandbir** [comment]
t-container改成@focus就好了
