### ISSUE TITLE
已经是utf-8的编码界面还是出现乱码

### ISSUE THREAD

**Issue by zcjunblog** [tzfun/vue-web-terminal#25]
**Bug description**
打印的是子进程标准输出, 控制台上看console是没有问题的 组件上显示的符号成了乱码

**Screenshot**
如图  作者哥帮忙看看
 ![](https://s3.bmp.ovh/imgs/2023/01/05/16e11c78f49bb955.png)

**Reproduce environment:**
 - windows
 - chrome
 - electron18.3.5

**Comment by tzfun** [comment]
这个是ANSI转译码，你应该是直接将进程输出打印到了Terminal中，此版本的Terminal组件暂不支持ANSI码翻译，这个工作量比较大，建议你在打印输出之前先简单处理：过滤掉ANSI Code，规则可参考：[rtfm / Xterm / Escape Sequences](http://rtfm.etla.org/xterm/ctlseq.html)

ANSI转译功能计划在Shell组件中支持，届时会支持部分 样式显示、光标控制、输入输出控制等功能。
