### ISSUE TITLE
No way to customize autocomplete

### ISSUE THREAD

**Issue by michaelKurowski** [tzfun/vue-web-terminal#28]
**Feature or optimization description**
I can't see a way to write own autocomplete. :thinking: 

I can't find any event/callback that would let me do my own search. The `tabKeyHandler` example in the docs is limited to limits replacing the `helpCmd`, which isn't really the case I'm speaking of.
I've tried to find some workarounds like changing `command-store` prop when the Tab is being pressed, but looks like this property is ignored after the terminal is mounted.

**Applicable scene**
Current system for autocomplete looks smooth for commands, but not their arguments. Let's assume that we have a command `some-command <path>`. I won't be able to autocomplete path, which quickly gets tedious when commands like `cd` get to be used quite often.

PS:
Thank you @tzfun for the amazing piece of software, that you've created. It really fills a neat niche.

**Comment by tzfun** [comment]
I have roughly understood your requirements. Can you add a custom search function attribute `searchHandler` to solve your problem? You can customize the search process, but there is a lot of work to do. I need to finish the Spring Festival to add it.

**Comment by michaelKurowski** [comment]
A customizable searchHandler would be just fine, thanks!

**Comment by tzfun** [comment]
`2.1.8` and `3.1.4` versions are supported @michaelKurowski
