### ISSUE TITLE
clone后编译会直接报错

### ISSUE THREAD

**Issue by deyihu** [tzfun/vue-web-terminal#29]
**Bug description**

**Steps to reproduce**

**Screenshot**

![I2XU(LM`XKWI2{(L}$ 5ML9](https://user-images.githubusercontent.com/25998927/219539783-69695564-5f9b-4b50-8eb0-b1f75d1fd611.png)

看着像是少了css-loader的依赖，比如node-sass

**Reproduce environment:**
 - Version [e.g. 2.0.4]

**Detailed Description**

**Comment by tzfun** [comment]
build脚本是之前打包测试的时候留下的，忘记改了，打包用这个脚本：`yarn run build-cli`
