### ISSUE TITLE
关于api设计的问题

### ISSUE THREAD

**Issue by deyihu** [tzfun/vue-web-terminal#30]
**Bug description**

**Steps to reproduce**

**Screenshot**

![9R6)DI)90H@L) _}{@~}PZM](https://user-images.githubusercontent.com/25998927/219540055-a40c0ef9-50f9-4165-9e8f-0f71543d8e74.png)

**Reproduce environment:**
 - Version [e.g. 2.0.4]

**Detailed Description**

应该将TermialObj的方法等 includes到组件内

```js
const terminal=this.$refs.terminal.pushMessage();

```

而不是目前这种，而不是全局的收集器，如果页面有大量的组件，光是起名字就挺麻烦的了

**Comment by tzfun** [comment]
我确实也发现了这个全局API的弊端，打算在下个大版本改掉，目前为了兼容考虑`2.1.x`版本暂时不动。感谢建议，前端本身我不太在行，有其他优化建议欢迎向我提出或者参与PR😄

**Comment by deyihu** [comment]
> 我确实也发现了这个全局API的弊端，打算在下个大版本改掉，目前为了兼容考虑`2.1.x`版本暂时不动。感谢建议，前端本身我不太在行，有其他优化建议欢迎向我提出或者参与PR😄

我待会提个pr过来来解决这个问题，当然会保证兼容性的

@tzfun
