### ISSUE TITLE
Support rename

### ISSUE THREAD

**Issue by tzfun** [tzfun/vue-web-terminal#38]
**支持修改`name`属性**

在多窗口场景下为了方便管理多个Terminal实例，需要动态修改实例的`name`属性，目前版本暂不支持。

**Comment by tzfun** [comment]
@birdmanmandbir 需要对Vue3 TS版本的同步支持

**Comment by birdmanmandbir** [comment]
不知道具体设计方式是什么样的? 最简单的就是组件暴露一个name属性就行

**Comment by tzfun** [comment]
@birdmanmandbir 之前的设计name属性已经暴露了，但还需要在name修改时重新注册`TerminalObj`，name是一个Terminal的事件key，目前的版本修改了name相应的事件就无效了。只需要监听name值，然后在 TerminalObj 中Unregister oldName and register newName，你可以参考我vue2分支中的提交

**Comment by tzfun** [comment]
`2.1.8`和`3.1.4`版本已支持
