### ISSUE TITLE
vue3.0里使用报错

### ISSUE THREAD

**Issue by 18578242152** [tzfun/vue-web-terminal#42]
**Bug description**

**Steps to reproduce**

**Screenshot**
<img width="756" alt="Screen Shot 2023-03-06 at 2 26 08 PM" src="https://user-images.githubusercontent.com/107911122/223034749-67d358a2-cbb9-46c8-9d2f-e8c6c8e3f150.png">

**Reproduce environment:**
 - Version [e.g. 2.0.4]

**Detailed Description**
本地运行之后，初始化就报错

**Comment by tzfun** [comment]
看堆栈似乎是你的使用方法不对，请提供一下你的调用代码

**Comment by 18578242152** [comment]
就是在main.ts里面注册一下terminal，然后组件里面使用一下
<img width="1124" alt="Screen Shot 2023-03-06 at 3 49 57 PM" src="https://user-images.githubusercontent.com/107911122/223049671-eb08d32c-df96-4b18-81fa-df868ac4c964.png">

**Comment by tzfun** [comment]
你的terminal版本是多少？确认一下是`3.x.x`版本吗，最好使用最新版`3.1.3`

**Comment by 18578242152** [comment]
巧了，我正好用的是3.1.2，刚试了下3.1.3没问题，感谢
