### ISSUE TITLE
使用界面出现undefined，并且无法显示文字

### ISSUE THREAD

**Issue by littlepoi** [tzfun/vue-web-terminal#43]
![image](https://user-images.githubusercontent.com/45566413/225213442-c0e398f6-2fb7-4999-9901-3444cd258949.png)
![image](https://user-images.githubusercontent.com/45566413/225213535-3b83f5ae-deb5-4bb4-bc5e-4f877dd69c7c.png)

**Comment by littlepoi** [comment]
我使用的是2.1.3版本，我是将demo中的LocalTerminal.vue文件拿出来使用了，但是界面显示就是这样的。

**Comment by tzfun** [comment]
你用`2.1.6`还有这个问题吗？

**Comment by littlepoi** [comment]
![image](https://user-images.githubusercontent.com/45566413/225226210-7bf5b3ab-7679-4fc1-9e9f-755ec541378f.png)
![image](https://user-images.githubusercontent.com/45566413/225226240-b5a9913f-e3fa-49db-b91e-cf3831f1806f.png)
也有这个问题，目前不太明白是哪里的问题。我单独用这个组件是正常的，和项目一起跑就会这样。

**Comment by tzfun** [comment]
在线demo[https://tzfun.github.io/vue-web-terminal/](https://tzfun.github.io/vue-web-terminal/)用的就是这一份代码，版本是2.1.3，刚刚在sandbox创建了一个2.1.3版本的空工程 [https://codesandbox.io/s/holy-monad-fzn3h4](https://codesandbox.io/s/holy-monad-fzn3h4)，也没有复现你的问题，怀疑是你所在环境影响到了，可以提供一下你的依赖列表吗

**Comment by littlepoi** [comment]
[package.json.txt](https://github.com/tzfun/vue-web-terminal/files/10976727/package.json.txt)
我有试过用demo的那个项目，把我的package.json复制过去，除了@vue/cli-plugin-babel这个包要使用4.5.0版本之外，其他的都没有问题，组件也可以正常使用。就是在项目里会出现这种问题。

**Comment by littlepoi** [comment]
![image](https://user-images.githubusercontent.com/45566413/225228491-5a8b6dde-a007-4042-a8bd-44c2bdac9c43.png)
然后，我按照git上的文档创建demo，只有2.0.8版本可以正常使用。之后的版本都会出现这个undefined和文字无法显示的问题。

**Comment by tzfun** [comment]
初步猜测是 slot 组件的支持兼容问题，我先排查一下

**Comment by tzfun** [comment]
原因找到了，是Vue官方在`2.6.13`版本对vue的slotRender修改导致，详情见：[https://github.com/vuejs/vue/issues/12153](https://github.com/vuejs/vue/issues/12153)

本terminal插件是在`2.6.14`环境编译的，如果你的项目中使用低于此版本的 vue和 vue-template-compiler 就会出现slot位置为undefined的问题。

解决办法：**将项目中的 vue 和 vue-template-compiler 版本提升至 2.6.13 以上，比如`2.6.14`**

**Comment by littlepoi** [comment]
好的，十分感谢！(*╹▽╹*)

**Comment by littlepoi** [comment]
你好，我觉得还是有点问题
![image](https://user-images.githubusercontent.com/45566413/227420609-af1e1de8-1594-465f-97cb-8fe61b4665e1.png)
![image](https://user-images.githubusercontent.com/45566413/227420789-306aaafb-6022-47da-af85-a131d164d6b4.png)
![image](https://user-images.githubusercontent.com/45566413/227420897-616a13c5-64aa-4199-91ef-d0a766c21c18.png)
![image](https://user-images.githubusercontent.com/45566413/227421055-565c323d-f97b-4ff0-a300-55894488764e.png)
我现在使用的版本是2.1.0

**Comment by tzfun** [comment]
项目中使用slot和依赖中使用slot是不太一样的，依赖使用slot引入到你项目中是经过我这边编译的，我编译时的vue-compiler规则不一样引入时的代码也会不一样，而你本地的slot是经过本地compiler编译的，自己使用上是ok的，但如果引入到别的项目是不确定的。出现这个问题的原因就是不同版本的compiler编出来的代码不一样造成。@littlepoi

**Comment by littlepoi** [comment]
> 项目中使用slot和依赖中使用slot是不太一样的，依赖使用slot引入到你项目中是经过我这边编译的，我编译时的vue-compiler规则不一样引入时的代码也会不一样，而你本地的slot是经过本地compiler编译的，自己使用上是ok的，但如果引入到别的项目是不确定的。出现这个问题的原因就是不同版本的compiler编出来的代码不一样造成。@littlepoi

好的，谢谢。因为项目限制我不能随意升级vue的版本，我再想想别的办法。
