### ISSUE TITLE
Make callbacks asynchronous

### ISSUE THREAD

**Issue by michaelKurowski** [tzfun/vue-web-terminal#44]
**Feature or optimization description**
Make callbacks to VueWebTerminal asynchronous

**Applicable scene**
If a terminal represents a shell on a remote machine then it's very hard to overwrite callbacks since they can't wait for an asynchronous request to be fulfiled.

https://github.com/tzfun/vue-web-terminal/issues/28 is a good example.
If autocomplete depends on files paths (i.e. in `cat` command), then it shouldn't be necessary to send whole filesystem of the target computer to the browser just to implement autocomplete. If the search callback would be asynchronous, then it would be possible to just send the request and the VueWebTerminal would wait for the data to be ready.

**Comment by tzfun** [comment]
@michaelKurowski This is a very good suggestion 👍🏻 In the future, I will plan to transform these handler methods into asynchronous implementations, but methods like `command-formatter` and `command-store-sort` that do not require asynchronization will still maintain synchronous implementations .

**Comment by tzfun** [comment]
@michaelKurowski The logic of command execution is asynchronous by default. Currently, the synchronous implementation methods are some function in attributes. Are there other places that need asynchronous transformation in your application scenario?

**Comment by tzfun** [comment]
The latest versions `2.1.10` and `3.1.6` already support this feature
