### ISSUE TITLE
onKeydown事件在使用Flash时，失焦后失效

### ISSUE THREAD

**Issue by private14** [tzfun/vue-web-terminal#46]
用的2.1.10版本，在Flash未结束的时候，如果这时候失去焦点，onKeydown事件会失效。
本来想用onKeydown实现ctrl^c结束执行的功能，但是发现这个问题，请教

**Comment by tzfun** [comment]
是有这样一个设定的，失去焦点是不应该再触发这个窗口的on-keydown事件，否则在多个窗口场景下会出现多个terminal实例接收到on-keydown事件，所以设定成仅**活跃**的窗口才能触发该事件
