### ISSUE TITLE
Show Header false not working.

### ISSUE THREAD

**Issue by akshaysinghtk14** [tzfun/vue-web-terminal#48]
**Bug description**
I have given :show-header="false" in vue-web-terminal @2.1.10 but my whole terminal is hidden.

**Steps to reproduce**

**Screenshot**
 <Terminal
          name="my-terminal"
          :context="'--'"
          :title="''"
          :show-header = "false"
          :initLog = "initLog"
          @exec-cmd="onExecCmd"
        ></Terminal>

**Reproduce environment:**
 - Browser Chrome
 - Version 2.1.10

**Detailed Description**

**Comment by tzfun** [comment]
In my case, version 2.1.10 is working normally, and it is also good in the [demo](https://tzfun.github.io/vue-web-terminal/), can you provide your complete code and screenshots?

**Comment by 246859** [comment]
This is due to the problem caused by the box positioning of the terminal. When you set the show header to false, you should set a fixed height for the terminal parent box, otherwise the box height will disappear naturally if it is 0
