### ISSUE TITLE
在type等于code模式下，回显带有xml标签信息时，xml标签没有正常显示，审查元素后发现xml标签被渲染成了dom元素。希望可以在code模式下正常显示xml标签信息

### ISSUE THREAD

**Issue by xiuyiliu** [tzfun/vue-web-terminal#50]
**Bug description**

**Steps to reproduce**

**Screenshot**

**Reproduce environment:**
 - Version [e.g. 2.0.4]

**Detailed Description**

**Comment by tzfun** [comment]
`2.1.12`和`3.1.8`已修复此问题
