### ISSUE TITLE
动态修改窗口大小

### ISSUE THREAD

**Issue by HZC-AND** [tzfun/vue-web-terminal#51]
**Feature or optimization description**
建议增加动态修改窗口大小的功能。
**Applicable scene**
将其嵌入在分割页面中的其中一个页面，希望其能够跟随分割页面长宽变化。

**Comment by tzfun** [comment]
收到建议，下个版本加上 😄 

对于 ”希望其能够跟随分割页面长宽变化“ 这个现在是可以做到的啊，你控制父元素的长宽，窗口会自动填充父元素，长宽也会随之变化

**Comment by HZC-AND** [comment]
谢谢您的回复😁

drag-conf的长宽配置为100%是相对于整个浏览器页面的，不太清楚如何相对于父元素div进行填充。可否给出部分引导？非常感谢。

**Comment by tzfun** [comment]
你可以手动给窗口套一个父元素，不过这样就不能使用拖拽了，相当于窗口是固定在父元素内。

```vue
<div style="width: 700px;height: 400px;">
  <terminal
      name="test"
      show-header
      @exec-cmd="onExecCmd">
  </terminal>
</div>
```

resize是一个不错的建议，我尽快写完发布pre-release

**Comment by HZC-AND** [comment]
我尝试过这样操作，但是却没有效果，第二个图片中有背景颜色的那部分是它的父元素。

![image2](https://github.com/tzfun/vue-web-terminal/assets/24476781/21dd8846-5352-4a1b-aa24-ad05e04cb595)

![imag1](https://github.com/tzfun/vue-web-terminal/assets/24476781/5e4a869d-3a72-408b-8bf1-3fb9cb0313aa)

**Comment by HZC-AND** [comment]
通过对.t-container添加position:relative !important; 可实现填充，定位出问题在css定位布局上。

**Comment by tzfun** [comment]
这确实是个bug，下个版本一起修复更出，感谢 👍

**Comment by tzfun** [comment]
`2.1.12`和`3.1.8`版本以支持此功能，并修复了无法填充父元素的bug

**Comment by HZC-AND** [comment]
非常感谢😁
