### ISSUE TITLE
Unable to copy values from table form of data.

### ISSUE THREAD

**Issue by akshaysinghtk14** [tzfun/vue-web-terminal#52]
**Bug description**
Unable to copy value from table form of data.

**Steps to reproduce**
1. Go to 'https://tzfun.github.io/vue-web-terminal/?cmd=table'
2. copy value from any cell
3. paste
4. Didn't get desired results.

**Screenshot**

**Reproduce environment:**
 - OS: Windows
 - Browser Chrome
 - version ^2.1.10

**Detailed Description**

**Comment by tzfun** [comment]
You need to use the right-click to copy the content, if you use ctrl+c will trigger the cursor input.

**Comment by tzfun** [comment]
Copy any content method:
1. Select content by cursor.
2. Right-click to copy it.

If you want to paste some things to input:
1. Copy content from some where.
2. Get input focus.
3. Use `ctrl+v` or right-click to paste the contents of the clipboard.
4. If you use right-click, you need authorize the browser to read the clipboard on this page, and the website must be 'https'.
