### ISSUE TITLE
使用vue3版本的时候，打中文光标位置不对

### ISSUE THREAD

**Issue by Chen-Haobo001** [tzfun/vue-web-terminal#53]
![image](https://github.com/tzfun/vue-web-terminal/assets/126689743/6a44d3de-1b8c-48d7-ae71-5bfb3e3b600d)

描述：
使用中文输入法，光标会重新回到第一个字，然后在你输入的时候不断后移

**Comment by tzfun** [comment]
我在Mac和Windows上分别测试了一下，用的vue3最新版本，没有出现这个问题，这应该和输入法有关系，因为在预置内容时是输入法控制光标，只有输入结束后才到浏览器控制，而插件的光标依赖于检测浏览器的光标（插件光标并非真实的光标）。

Mac下用搜狗输入法
<img width="1034" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/34815354/a764910e-4a2d-45b9-b64c-7ce19f0b7f44">

Mac下用自带输入法
<img width="1040" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/34815354/a0d6d7d9-a1db-41da-bb48-9391bae5bf82">

Windows 10下用系统自带输入法
![IMG_8199](https://github.com/tzfun/vue-web-terminal/assets/34815354/e54d4b97-4fd3-4a8c-bad8-502f587fdc28)

**Comment by Chen-Haobo001** [comment]
![动画](https://github.com/tzfun/vue-web-terminal/assets/126689743/4cc2034e-c9f9-4245-b955-6afe8833d01b)
我又用vite创建了最新的vue3,然后又使用还是有这个问题,不知道是我的输入法问题还是什么浏览器问题,我发现空白行输入中文的时候没有像你一样的预览效果，令人疑惑

你的在线demo我使用是正常
代码如下
``` js
// app.js
<template>
  <div class="cmd">
    <terminal name="my-terminal" @exec-cmd="onExecCmd"></terminal>
  </div>
</template>
<script setup>
import Terminal from "vue-web-terminal";
const onExecCmd = (key, command, success, failed) => {
  if (key === "fail") {
    failed("Something wrong!!!");
  } else {
    let allClass = ["success", "error", "system", "info", "warning"];

    let clazz = allClass[Math.floor(Math.random() * allClass.length)];
    success({
      type: "normal",
      class: clazz,
      tag: "成功",
      content: command,
    });
  }
};
</script>
<style>
.cmd {
  width: 80vh;
  height: 500px;
}
</style>

```

**Comment by Chen-Haobo001** [comment]
我是win10系统,我用vite创建了最新版vue3,还是有这个问题,使用vue cli 创建vue2就没有这个问题,令人疑惑,不知道是输入法问题阿还是浏览器问题

**Comment by tzfun** [comment]
> 我是win10系统,我用vite创建了最新版vue3,还是有这个问题,使用vue cli 创建vue2就没有这个问题,令人疑惑,不知道是输入法问题阿还是浏览器问题

你能创建一个sandbox吗，我本地用vite也创建了一个项目试了还是没问题

**Comment by Chen-Haobo001** [comment]
我创建了一个vite-vue3的sandbox没有任何问题,看来是我的本地环境问题
