### ISSUE TITLE
init-log 为 null 终端无法输入

### ISSUE THREAD

**Issue by rockmelodies** [tzfun/vue-web-terminal#54]
**Bug description**

**Steps to reproduce**

**Screenshot**

**Reproduce environment:**
 - Version [e.g. 2.0.4]

**Detailed Description**

init-log 为 null 终端无法输入

**Comment by tzfun** [comment]
我这边用最新版本无法复现这个问题，请提供一下你的vue版本和terminal版本，以及实现代码
