### ISSUE TITLE
关于功能使用

### ISSUE THREAD

**Issue by shuiYe-704265085** [tzfun/vue-web-terminal#55]
请问目前是不是不支持websocket方式实时与后端进行交互，数据全部由后端进行提供

**Comment by tzfun** [comment]
数据格式是需要后端提供的，是可以使用websocket，如果你想要实现的是像 XTerm 那样的完全不经过后端处理直接ssh与服务器交互的效果（需转译ANSI），这个插件不适合这样的场景，它更适合命令式的执行场景，比如：redis、etcd客户端，前端管理终端等等。
