### ISSUE TITLE
Vue3版本使用Vite + TypeScript进行重构

### ISSUE THREAD

**Issue by tzfun** [tzfun/vue-web-terminal#57]
* 使用 TS 代替 JS
* 添加 .d.ts 支持类型约束与提示
* 计划长期支持版本

**Comment by elasticdotventures** [comment]
为什么这个问题仍然悬而未决？

**Comment by elasticdotventures** [comment]
这个问题完结了吗？

**Comment by tzfun** [comment]
> 这个问题完结了吗？

已经在发布beta版本测试了，测试完之后就会发布，这次vue3版本的改动比较大需要足够的测试，因个人工作原因可能会有一些慢，不过现在已经接近尾声了，预计这周内发布新版本

**Comment by tzfun** [comment]
重构完成，新版本：`3.2.2`
