### ISSUE TITLE
vue2.6.12 version: v2.1.12无法使用

### ISSUE THREAD

**Issue by EGsnn** [tzfun/vue-web-terminal#59]
**Bug description**
这个版本打包后无法使用，安装vue2.0 + vue-web-terminal 用demo的例子。无法使用

**Comment by EGsnn** [comment]
解决第一步，把里面的@引用符号去掉，换成相对路径。

**Comment by tzfun** [comment]
> **Bug description**
> 这个版本打包后无法使用，安装vue2.0 + vue-web-terminal 用demo的例子。无法使用

我的生产环境中一直使用的这个版本，没有你说的这个情况，是不是你的工程里有依赖冲突，或者打包配置问题？

**Comment by EGsnn** [comment]
确实是我本地出现了问题
