### ISSUE TITLE
数据量过大页面卡顿

### ISSUE THREAD

**Issue by David-XIa001** [tzfun/vue-web-terminal#60]
数据超过200条页面就开始卡了,这个是正常的吗
可否提供一个参数限制最大数据量，类似队列，先进先出

**Comment by tzfun** [comment]
200条页面卡不太正常，除非每一条数据的数据量都很大，我的这边平时使用下来1000条数据都是ok的。
限制最大数据量之前版本有做过后来给去掉了，当时觉得用处不大，目前看来卡顿影响更大，下个版本我加回来吧

**Comment by tzfun** [comment]
已发布`2.2.0`和`3.2.2`版本支持
