### ISSUE TITLE
希望可以支持 Ctrl/Command + c 复制功能

### ISSUE THREAD

**Issue by lilqilie** [tzfun/vue-web-terminal#61]
**Feature or optimization description**
##Current Behavior
 在terminal界面选中一段内容后，按下Ctrl/Command 键会自动获取焦点，导致取消选中，无法完成键盘复制行为。
## Expected Behavior
Ctrl/Command + c 完成复制功能比较符合浏览器环境的用户习惯，可以有效提高用户体验，希望可以支持 Ctrl/Command + c 复制功能。

**Comment by tzfun** [comment]
已发布`2.2.0`和`3.2.2`版本支持
