### ISSUE TITLE
建议能够实现一下Vim

### ISSUE THREAD

**Issue by MrLeungE1** [tzfun/vue-web-terminal#62]
**Feature or optimization description**

**Applicable scene**

**Comment by tzfun** [comment]
要实现Vim需要解析ansi code，这个实现机制和插件当前的实现方式截然不同，在此插件基础上实现无异于做一个Web Vim插件，我觉得这个就没必要重复造轮子了，市面上已有非常优秀的插件，你可以在你的应用中接入其他Vim编辑器。

**Comment by MrLeungE1** [comment]
好的，感谢回复
