### ISSUE TITLE
选中字符后按鼠标右键复制，再执行粘贴行为，在复制内容上会出现额外的 “a 你”字符

### ISSUE THREAD

**Issue by lilqilie** [tzfun/vue-web-terminal#63]
**Bug description**
选中字符后按鼠标右键复制，再执行粘贴行为，在复制内容上会出现额外的 “a 你”字符

**Steps to reproduce**
1. 在termnial中输入字符
2. 选中自己输入的字符
3. 鼠标右键完成复制
4. 按cmd+v后，完成粘贴，此时在复制内容上会出现额外的 “a 你”字符

**Comment by tzfun** [comment]
已发布`2.2.0`和`3.2.2`版本修复
