### ISSUE TITLE
pushMessage时可以设置是否换行结尾

### ISSUE THREAD

**Issue by Xuwznln** [tzfun/vue-web-terminal#66]
**Feature or optimization description**
pushMessage时可以设置是否换行结尾，增加一个参数或者一个新的类型

**Applicable scene**
控制台输出分片的消息时，中间没有换行，但是pushMessage后会看到换行内容

**Comment by tzfun** [comment]
换行需要解析特定的换行符，你希望有一个参数可以在pushMessage时不对 \n \r \t等进行转译吗

**Comment by Xuwznln** [comment]
使用websocket传输ssh的指令输出时，如果指令太长，会发送两条消息，我现在防止消息太长是每收到一次消息就pushMessage()一次，显示效果上两个message之间是空开的，能不能加一个参数指定不空开，或者可以不可以多一个appendMessage()函数

**Comment by tzfun** [comment]
这种情况你可以尝试使用flash来实现：https://github.com/tzfun/vue-web-terminal#flash

当然添加一个appendMessage这也是一个不错的建议，后续考虑加上这个接口

**Comment by tzfun** [comment]
已发布`2.2.0`和`3.2.2`版本支持
