### ISSUE TITLE
增加折叠线，视觉区分每次命令界限

### ISSUE THREAD

**Issue by redisviewer** [tzfun/vue-web-terminal#75]
**Feature or optimization description**
<img width="1006" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/12822830/134a0e92-bf16-4249-b0c6-4ae48fb3731d">
建议参考windterm或者idea增加这种视觉折叠线，或者区域色块，

视觉上更容易感知每次命令与结果，明确区分每次命令的边界
另外可以折叠起来的话，有些场景下很有必要

感谢大佬的作品，真的很好很用心

**Comment by tzfun** [comment]
我尝试去加了折叠线，发现这个功能并不太适合插件当前的设计，可以折叠的log需要在同一个组group，但插件当前设计是没有组的概念的，每一条log都是单独的一个记录，甚至是一条命令也是单独的一条记录，目前无法判断它们应不应该被归纳入一个组，为了提供更灵活的控制能力，用户可以使用回调、API向log追加任意内容，如果加入组的概念会让这些API变得复杂，一些新用户可能难以理解。

如果这是一个实用性工具，我会选择开发这个功能，确实会给用户带来更好的视觉体验，但这是一个插件，我认为它应该是简单的、易上手的。为了提升这部分视觉体验让API变得复杂，并且可能带来不兼容，目前我的评估是不合适的。

当然可能我没有找到更合适的解决方案，毕竟我在前端领域也不是很熟悉，如果你或者其他开发者有更好的方案可以提交PR，欢迎大家一起来构建它。

**Comment by tzfun** [comment]
经过几次尝试，我找到了比较折中的方案，此功能在下一个版本提供

**Comment by tzfun** [comment]
已在 `2.2.4` 和 `3.2.6`版本更新
