### ISSUE TITLE
调整行高后，指令提示框无法自动隐藏

### ISSUE THREAD

**Issue by redisviewer** [tzfun/vue-web-terminal#76]
margin-top调小
margin-bottom调小
修改默认行高后，导致命令提示框无法自动隐藏（必现）
<img width="1280" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/12822830/129e7d0a-1af4-4af1-870a-dc2adedd72d5">
行高调小后，首行无法自动隐藏提示框

建议参数化行高，内部计算逻辑读取参数进行自动隐藏

**Comment by tzfun** [comment]
已在 `2.2.4` 和 `3.2.6`版本更新
