### ISSUE TITLE
空行敲击空格问题

### ISSUE THREAD

**Issue by redisviewer** [tzfun/vue-web-terminal#80]
![image](https://github.com/tzfun/vue-web-terminal/assets/12822830/6b563617-e0e5-4d15-a3dc-4eebe86bf76e)

空行敲击空格，光标没有后移，好像没有敲进去，
但是继续敲字幕，空格又出现了

**Comment by tzfun** [comment]
已在 `2.2.4` 和 `3.2.6`版本更新
