### ISSUE TITLE
当输入中文字符时，出现光标移动的问题！

### ISSUE THREAD

**Issue by lihanqiang** [tzfun/vue-web-terminal#82]
输入中文命令如： cd 桌面，光标位置乱跑，最终变为：桌面。
![662603398d554_662603e96efe9](https://github.com/tzfun/vue-web-terminal/assets/16048224/ca82793f-3e04-46b1-9bde-e2be46f948f4)

**Comment by lihanqiang** [comment]
系统：win11 23H2，vue2

**Comment by tzfun** [comment]
这个是输入法预置字符发生了占位引起的，键入中文后应该就正常了吧，这个是系统或应用的控制，插件无法控制，其他一些使用者也遇到了这个情况，目前暂不影响使用

**Comment by lihanqiang** [comment]
@tzfun 就是影响使用啊，我先输入英文后输入中文，位置都变了。意思是先输入中文再输入英文再调整位置，肯定不能啊！！望修复或者开放api。。。

**Comment by tzfun** [comment]
你看一下demo里面有这个问题吗？
https://tzfun.github.io/vue-web-terminal/

**Comment by lihanqiang** [comment]
thanks for replying! 👍 @tzfun

**Comment by maxwellday** [comment]
麻烦问下，最后咋解决的

**Comment by lihanqiang** [comment]
作者没解决&nbsp;


С?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月28日(星期一) 中午11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tzfun/vue-web-terminal] 当输入中文字符时，出现光标移动的问题！ (Issue #82)














 
麻烦问下，最后咋解决的

**Comment by tzfun** [comment]
@lihanqiang @maxwellday 
中文输入问题已发布 `3.3.4-rc.4` 版本解决，此版本与上个release版本 `3.3.3` 差别仅在于解决中文输入问题
