### ISSUE TITLE
Demo 页的一些小 Bug 与建议

### ISSUE THREAD

**Issue by MoYuan-CN** [tzfun/vue-web-terminal#84]
![image](https://github.com/tzfun/vue-web-terminal/assets/109946426/61171c2f-6138-40af-82e3-a59349675de8)
建议按照一定的顺序排列，例如 `system` `info` `success` `warning` `error`

![image](https://github.com/tzfun/vue-web-terminal/assets/109946426/f7b343d1-b710-46eb-b8a1-39e1cefefdf8)
文本错误：`vue-wen-terminal` -> `vue-web-terminal`（wen）

![image](https://github.com/tzfun/vue-web-terminal/assets/109946426/84a0b75d-ec62-433b-9f00-af668ee7ad61)
文本错误：`当作 Falsh 使用` -> `当作 Flash 使用`（Falsh）

**Comment by tzfun** [comment]
已在 `2.2.4` 和 `3.2.6`版本更新
