### ISSUE TITLE
能否添加js预置命令，等用户输入后面的内容之后，点击enter键，再触发exec-cmd事件

### ISSUE THREAD

**Issue by mswater** [tzfun/vue-web-terminal#85]
目前遇到这样一个问题，看开放文档，感觉并不支持，礼貌询问一下能否支持此需求

例：“SS 用户输入”，SS是js写入的，后面用户输入是等待用户输入的

**Comment by mswater** [comment]
补充说明，不是ask那种形式     就是用户先选择预置命令，再去补全后面的自定义内容，这样才组成一条完整的指令

**Comment by tzfun** [comment]
这个需求听起来有点“特殊”，在什么场景下会用到？

**Comment by mswater** [comment]
目前正在做的一个产品，预置命令比较多，因此提供了用户点击选择命令的功能。因此就出现了用户选一部分命令，自己输入一部分命令的需求。

**Comment by mswater** [comment]
我理解的思路是，允许push一条暂不执行的命令，并且可以在这个命令上追加，确定追加完毕后手动触发exec-cmd事件

**Comment by tzfun** [comment]
可以，这个功能计划在下一个版本支持

**Comment by tzfun** [comment]
已在 `2.2.4` 和 `3.2.6`版本更新

**Comment by mswater** [comment]
👍🏻
