### ISSUE TITLE
语法提示多条展示

### ISSUE THREAD

**Issue by redisviewer** [tzfun/vue-web-terminal#86]
<img width="1142" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/12822830/493726a1-399a-4b96-bd69-a56c7ab1e97f">
<img width="1363" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/12822830/5eb79b2f-07c6-48ee-95fe-eac6870395af">
建议开发类似warp、windterm这种语法提示，根据光标走的提示
vue-web-terminal如果能开放这样的接口，那简直完美了

**Comment by tzfun** [comment]
已发布 `2.3.0` 和 `3.3.0` 更新
