### ISSUE TITLE
如果在终端输入内容，但是不执行，而是关闭终端，再次开启的时候我只有先execute（）  然后将terminalLog清空，有没有啥方法可以直接初始化啊

### ISSUE THREAD

**Issue by tzfun** [tzfun/vue-web-terminal#9]
大佬，现在如果在终端输入内容，但是不执行，而是关闭终端，再次开启的时候我只有先execute（）  然后将terminalLog清空，有没有啥方法可以直接初始化啊

_Originally posted by @18030705033 in https://github.com/tzfun/vue-web-terminal/issues/2#issuecomment-1286577654_

**Comment by 18030705033** [comment]
不执行直接关闭的话，上次输入的东西并不会消失

**Comment by tzfun** [comment]
没太动你存在的问题，关闭了输入的内容不会存在了啊，“输入的东西”以什么样的形式存在？

**Comment by 18030705033** [comment]
比如我输入abc 但是没有按下回车执行，然后就直接关闭，再次打开的时候，我期望的是初始化的界面（就是没有任何历史遗留），但是这边展示的会是残留上次输入未执行的

**Comment by tzfun** [comment]
> 比如我输入abc 但是没有按下回车执行，然后就直接关闭，再次打开的时候，我期望的是初始化的界面（就是没有任何历史遗留），但是这边展示的会是残留上次输入未执行的

你应该是没有销毁组件，建议：
1. 检查一下页面内是否设置有缓存；
2. 你是否用到了v-if和v-show？如果是v-show来打开和关闭terminal并不是真正的移除dom，用v-if才会移除dom重新挂在执行terminal的初始化。

**Comment by 18030705033** [comment]
大佬，你的最新版本是多少啊？我看md有拖拽和全屏了，但是最新的版本好像是3.0.3吧，然后全屏和拖拽都不行呢？拖拽的dragConf.enable是在哪里设置呢？

**Comment by 18030705033** [comment]
npm install vue-web-terminal@3.0.7 --save 下载不了啊   我现在把page-lock。json删除了以后重新下载 只有 npm install vue-web-terminal@3.0.3 --save可以下载  ，如果直接 npm install vue-web-terminal，下载下来的也是3.0.3

**Comment by 18030705033** [comment]
npm install vue-web-terminal@3.0.7 --save 下载不了啊   我现在把page-lock。json删除了以后重新下载 只有 npm install vue-web-terminal@3.0.3 --save可以下载  ，如果直接 npm install vue-web-terminal，下载下来的也是3.0.3

**Comment by tzfun** [comment]
> npm install vue-web-terminal@3.0.7 --save 下载不了啊 我现在把page-lock。json删除了以后重新下载 只有 npm install vue-web-terminal@3.0.3 --save可以下载 ，如果直接 npm install vue-web-terminal，下载下来的也是3.0.3

npm中央仓库最新的已经更到3.0.7（[https://www.npmjs.com/package/vue-web-terminal/v/3.0.7](https://www.npmjs.com/package/vue-web-terminal/v/3.0.7)），你可能是本地有缓存或者使用了类似淘宝cnpm、pnpm等国内仓库镜像，国内镜像同步有延迟，建议设置registry为npm中央仓库下载。

**Comment by 18030705033** [comment]
是的，已经下载下来3.0.7版本了，就是淘宝镜像的问题

**Comment by 18030705033** [comment]
现在全屏为啥会直接报这个错呢？
&nbsp;


小宾。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月24日(星期一) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tzfun/vue-web-terminal] 如果在终端输入内容，但是不执行，而是关闭终端，再次开启的时候我只有先execute（）  然后将terminalLog清空，有没有啥方法可以直接初始化啊 (Issue #9)





  
npm install ***@***.*** --save 下载不了啊 我现在把page-lock。json删除了以后重新下载 只有 npm install ***@***.*** --save可以下载 ，如果直接 npm install vue-web-terminal，下载下来的也是3.0.3
  
npm中央仓库最新的已经更到3.0.7（https://www.npmjs.com/package/vue-web-terminal/v/3.0.7），你可能是本地有缓存或者使用了类似淘宝cnpm、pnpm等国内仓库镜像，国内镜像同步有延迟，建议设置registry为npm中央仓库下载。

**Comment by 18030705033** [comment]
点击全屏按钮报错：cannot read properties of undefined (reading 'requestFullscreen),最小化和关闭按钮没问题，前面做好的也不能用了

**Comment by 18030705033** [comment]
点击关闭和最小化能显示onclick传递的key，但也汇报错cannot read properties of undefined (reading 'requestFullscreen),最大化直接key都不能打印

**Comment by 18030705033** [comment]
开始用的v-if 但是v-if会报错
无法注册现有的 unable to register an existing terminal ：xxxx。（两个环境都是这样，pro环境报错但可以继续使用，dev将无法创建）这是名称要动态的吗，
用v-show的话可以清空init-log，假装初始化，但是如果有上次关闭前未执行语句，他会继续显示该语句

**Comment by 18030705033** [comment]
v-show就是通过key来配置，清空init-log，context，title

**Comment by tzfun** [comment]
> v-show就是通过key来配置，清空init-log，context，title

不知道你想实现的是不是demo中的效果，参考一下demo代码：[https://github.com/tzfun/vue-web-terminal/blob/demo/src/App.vue#L5](https://github.com/tzfun/vue-web-terminal/blob/demo/src/App.vue#L5)
