### ISSUE TITLE
建议折叠线API：全部折叠，全部展开

### ISSUE THREAD

**Issue by redisviewer** [tzfun/vue-web-terminal#92]
<img width="1280" alt="image" src="https://github.com/tzfun/vue-web-terminal/assets/12822830/86cc988d-f72d-4329-8586-384114f18a23">
建议折叠线API：全部折叠，全部展开

全部折叠后用户可以手动打开部分，进行对比数据...  便利型需求

**Comment by tzfun** [comment]
已发布 `2.3.0` 和 `3.3.0` 更新
